//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoporteTest1
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_por_depto
    {
        public Nullable<int> cantidadrep { get; set; }
        public string departmnto { get; set; }
    }
}
